version: "1"

refactor:
  # Collapse multi-line statements when they fit on one line
  skip: []

rule_settings:
  # Enable line collapsing rules
  enable:
    - merge-list-appends-into-extend
    - merge-dict-assign
    - merge-nested-ifs
    - use-fstring-fmt-method
    - remove-unnecessary-else
    - simplify-boolean-comparison
    - use-contextlib-suppress
    - use-named-expression
    - use-any
    - use-all
    - use-min-max
    - use-assigned-variable
    - inline-variable
    - extract-method

# Code style preferences
code_style:
  max_line_length: 200
  collapse_single_line: true

# Python version
python_version: "3.12"

