"""Core domain primitives, models, and protocols for AGENT-K.

@notice: |
    Core domain primitives, models, and protocols for AGENT-K.

@dev: |
    See module for implementation details and extension points.

@graph:
    id: agent_k.core
    provides:
        - agent_k.core
    pattern: core-facade

@agent-guidance:
    do:
        - "Use agent_k.core as the canonical home for this capability."
    do_not:
        - "Create parallel modules without updating @similar or @graph."

@human-review:
    last-verified: 2026-01-26
    owners:
        - agent-k-core

(c) Mike Casale 2025.
Licensed under the MIT License.
"""

from __future__ import annotations as _annotations

from .constants import (
    CHECKPOINT_INTERVAL_GENERATIONS,
    CONVERGENCE_THRESHOLD_GENERATIONS,
    DEFAULT_KAGGLE_MCP_URL,
    DEFAULT_MODEL,
    DISCOVERY_TIMEOUT_SECONDS,
    EVOLUTION_POPULATION_SIZE,
    EVOLUTION_TIMEOUT_SECONDS,
    KAGGLE_API_BASE_URL,
    MAX_COMPETITIONS_PER_SEARCH,
    MAX_CONCURRENT_SUBMISSIONS,
    MAX_EVOLUTION_GENERATIONS,
    MAX_MISSION_EVOLUTION_ROUNDS,
    MAX_RETRIES,
    MEMORY_SESSION_TTL_SECONDS,
    MISSION_PHASES,
    MUTATION_TYPES,
    PROTOTYPE_TIMEOUT_SECONDS,
    RESEARCH_TIMEOUT_SECONDS,
    RETRY_DELAY_SECONDS,
    SOLUTION_EXECUTION_TIMEOUT_SECONDS,
    SUBMISSION_TIMEOUT_SECONDS,
    VALID_COMPETITION_TYPES,
)
from .deps import BaseDeps, KaggleDeps
from .exceptions import (
    AdapterError,
    AgentError,
    AgentExecutionError,
    AgentKError,
    AuthenticationError,
    CompetitionError,
    CompetitionNotFoundError,
    ConvergenceError,
    DeadlinePassedError,
    EvolutionError,
    FitnessEvaluationError,
    GraphError,
    MemoryCapacityError,
    MemoryError,
    OutputValidationError,
    PhaseTimeoutError,
    PlatformConnectionError,
    PopulationExtinctError,
    RateLimitError,
    StateTransitionError,
    SubmissionError,
    ToolExecutionError,
)
from .fitness import FITNESS_FLOOR, coerce_metric_direction, fitness_to_score, score_to_fitness
from .models import (
    Checkpoint,
    CodeExecutorCall,
    Competition,
    CompetitionType,
    ErrorEvent,
    EvaluationMetric,
    EvolutionState,
    GenerationMetrics,
    KaggleMCPCall,
    LeaderboardAnalysis,
    LeaderboardEntry,
    LeaderboardSubmission,
    MemoryCall,
    MemoryEntry,
    MemoryState,
    MissionCriteria,
    MissionPlan,
    PhasePlan,
    PlannedTask,
    ResearchFindings,
    Submission,
    ToolCall,
    WebSearchCall,
)
from .protocols import PlatformAdapter
from .sage import Constraint, Default, Doc, Range
from .settings import AgentKSettings
from .types import (
    AgentDepsT,
    AsyncCallback,
    CompetitionId,
    ErrorCategory,
    EventCallback,
    FitnessScore,
    InputT_contra,
    JsonDict,
    LeaderboardRank,
    MemoryScope,
    MetricDirection,
    MissionId,
    MissionPhase,
    OutputT,
    OutputT_co,
    P,
    R,
    RecoveryStrategy,
    Score,
    StateT,
    TaskId,
    TaskPriority,
    TaskStatus,
    ToolResult,
    ToolType,
)

__all__ = (
    "CHECKPOINT_INTERVAL_GENERATIONS",
    "CONVERGENCE_THRESHOLD_GENERATIONS",
    "DEFAULT_KAGGLE_MCP_URL",
    "DEFAULT_MODEL",
    "DISCOVERY_TIMEOUT_SECONDS",
    "EVOLUTION_POPULATION_SIZE",
    "EVOLUTION_TIMEOUT_SECONDS",
    "KAGGLE_API_BASE_URL",
    "MAX_COMPETITIONS_PER_SEARCH",
    "MAX_CONCURRENT_SUBMISSIONS",
    "MAX_EVOLUTION_GENERATIONS",
    "MAX_MISSION_EVOLUTION_ROUNDS",
    "MAX_RETRIES",
    "MEMORY_SESSION_TTL_SECONDS",
    "MISSION_PHASES",
    "MUTATION_TYPES",
    "PROTOTYPE_TIMEOUT_SECONDS",
    "RESEARCH_TIMEOUT_SECONDS",
    "RETRY_DELAY_SECONDS",
    "SOLUTION_EXECUTION_TIMEOUT_SECONDS",
    "SUBMISSION_TIMEOUT_SECONDS",
    "VALID_COMPETITION_TYPES",
    "AdapterError",
    "AgentError",
    "AgentExecutionError",
    "AgentKError",
    "AuthenticationError",
    "CompetitionError",
    "CompetitionNotFoundError",
    "ConvergenceError",
    "DeadlinePassedError",
    "EvolutionError",
    "FitnessEvaluationError",
    "GraphError",
    "MemoryCapacityError",
    "MemoryError",
    "OutputValidationError",
    "PhaseTimeoutError",
    "PlatformAdapter",
    "PlatformConnectionError",
    "PopulationExtinctError",
    "RateLimitError",
    "StateTransitionError",
    "SubmissionError",
    "ToolExecutionError",
    "FITNESS_FLOOR",
    "coerce_metric_direction",
    "fitness_to_score",
    "score_to_fitness",
    "BaseDeps",
    "KaggleDeps",
    "Checkpoint",
    "CodeExecutorCall",
    "Competition",
    "CompetitionType",
    "ErrorEvent",
    "EvolutionState",
    "EvaluationMetric",
    "GenerationMetrics",
    "KaggleMCPCall",
    "LeaderboardAnalysis",
    "LeaderboardEntry",
    "LeaderboardSubmission",
    "MemoryCall",
    "MemoryEntry",
    "MemoryState",
    "MissionCriteria",
    "MissionPlan",
    "PhasePlan",
    "PlannedTask",
    "ResearchFindings",
    "Submission",
    "ToolCall",
    "WebSearchCall",
    "AgentKSettings",
    "Constraint",
    "Default",
    "Doc",
    "Range",
    "AgentDepsT",
    "AsyncCallback",
    "CompetitionId",
    "ErrorCategory",
    "EventCallback",
    "FitnessScore",
    "InputT_contra",
    "JsonDict",
    "LeaderboardRank",
    "MemoryScope",
    "MetricDirection",
    "MissionId",
    "MissionPhase",
    "OutputT",
    "OutputT_co",
    "P",
    "R",
    "RecoveryStrategy",
    "Score",
    "StateT",
    "TaskId",
    "TaskPriority",
    "TaskStatus",
    "ToolResult",
    "ToolType",
)
